import type { Item, CardType } from "@/types";

export type ExampleTemplate = {
  mapName: string;
  items: Omit<Item, "id" | "mapId" | "createdAt">[];
  connections: { sourceIndex: number; targetIndex: number; comment: string }[];
};

export const exampleMapTemplate: ExampleTemplate = {
  mapName: "Example — how MyMind works",
  items: [
    {
      title: "Which hosting provider should we use?",
      tags: [],
      dueDate: null,
      description: "A **decision** card. This is the question you need to commit to — the anchor the rest of the map is built around.",
      posX: 420,
      posY: 60,
      color: null,
      width: null,
      height: null,
      scale: null,
      status: null,
      cardType: "decision" as CardType,
    },
    {
      title: "Self-host on a VPS",
      tags: [],
      dueDate: null,
      description: "An **option** — a candidate answer to the decision above. Options are where the trade-offs live.",
      posX: 120,
      posY: 260,
      color: null,
      width: null,
      height: null,
      scale: null,
      status: null,
      cardType: "option" as CardType,
    },
    {
      title: "Use a managed platform",
      tags: [],
      dueDate: null,
      description: "Another **option**. Each option collects the assumptions it depends on and the risks it carries beneath it.",
      posX: 720,
      posY: 260,
      color: null,
      width: null,
      height: null,
      scale: null,
      status: null,
      cardType: "option" as CardType,
    },
    {
      title: "We will not exceed 1k users in year one",
      tags: [],
      dueDate: null,
      description: "An **assumption** — something believed but not verified. Assumptions are where decisions quietly go wrong. Naming this one makes it checkable later: if we blow past 1k users, this option collapses.",
      posX: 120,
      posY: 460,
      color: null,
      width: null,
      height: null,
      scale: null,
      status: null,
      cardType: "assumption" as CardType,
    },
    {
      title: "Vendor lock-in limits future flexibility",
      tags: [],
      dueDate: null,
      description: "A **risk** — something that could go wrong with the option above. Writing it down does not make it less likely, but it stops it being a surprise and keeps the trade-off honest.",
      posX: 720,
      posY: 460,
      color: null,
      width: null,
      height: null,
      scale: null,
      status: null,
      cardType: "risk" as CardType,
    },
    {
      title: "Competitor pricing survey, July 2026",
      tags: [],
      dueDate: null,
      description: "**Evidence** — something you actually know, with a source. Evidence is what turns an assumption into a fact. The managed platform's entry tier is 3x the VPS cost, which is what makes the assumption above worth testing.",
      posX: 420,
      posY: 640,
      color: null,
      width: null,
      height: null,
      scale: null,
      status: null,
      cardType: "evidence" as CardType,
    },
    {
      title: "What this map shows",
      tags: [],
      dueDate: null,
      description: "A **note**. The cards are the pieces; the connections are the argument.\n\nFollow the edges downward: the decision splits into two options, one option rests on an assumption, the other carries a risk, and evidence sits beneath both to test the trade-off. Every edge has a short comment so the map explains itself when you come back to it months later.",
      posX: 420,
      posY: 840,
      color: null,
      width: null,
      height: null,
      scale: null,
      status: null,
      cardType: "note" as CardType,
    },
  ],
  connections: [
    { sourceIndex: 0, targetIndex: 1, comment: "Considering" },
    { sourceIndex: 0, targetIndex: 2, comment: "Considering" },
    { sourceIndex: 1, targetIndex: 3, comment: "Only viable if this holds" },
    { sourceIndex: 2, targetIndex: 4, comment: "Known trade-off" },
    { sourceIndex: 3, targetIndex: 5, comment: "Tests this assumption" },
    { sourceIndex: 4, targetIndex: 5, comment: "Quantifies the cost" },
    { sourceIndex: 0, targetIndex: 6, comment: "Explains" },
  ],
};
